export const globalTheme = {
  token: {
    fontFamily: "var(--font-jakarta-sans), sans-serif",
    colorPrimary: "#ed6b23",
    colorPrimaryBorder: "#f6b591",
    colorLink: "#ed6b23",
    colorLinkHover: "#f39c6c",
  },
  components: {
    Menu: {
      horizontalItemHoverColor: "#2d2a70",
      horizontalItemSelectedColor: "#2d2a70",
    },
    Button: {
      fontFamily: "var(--font-jakarta-sans), sans-serif",
      defaultActiveBorderColor: "#c6591d",
      defaultActiveColor: "#c6591d",
      colorLinkActive: "#c6591d",
      colorPrimaryActive: "#c6591d",
      colorPrimaryTextActive: "#c6591d",
      defaultHoverBorderColor: "#f08448",
      defaultHoverColor: "#f08448",
      groupBorderColor: "#f08448",
      colorPrimaryHover: "#f08448",
      colorPrimaryTextHover: "#f08448",
      colorLink: "#ed6b23",
      colorPrimary: "#ed6b23",
      colorLinkHover: "#f39c6c",
      colorPrimaryBg: "#fbe1d3",
      colorPrimaryBgHover: "#f9ceb6",
      colorPrimaryBorder: "#f6b591",
      fontWeight: 700,
      paddingBlock: 12,
      paddingBlockLG: 14,
      paddingBlockSM: 6,
      paddingInline: 24,
      paddingInlineLG: 24,
      paddingInlineSM: 12,
      onlyIconSize: 16,
      onlyIconSizeLG: 24,
      onlyIconSizeSM: 12,
      contentFontSize: 14,
      contentFontSizeLG: 16,
      contentFontSizeSM: 12,
    },
    Switch: {
      colorPrimary: "#ED6B23",
      colorPrimaryHover: "#ED6B23",
      colorTextTertiary: "#29313414",
      colorTextQuaternary: "#29313414",
    },
    DatePicker: {
      activeBorderColor: "#293134",
      hoverBorderColor: "#333d41",
      cellHoverWithRangeBg: "#fbe1d3",
      cellRangeBorderColor: "#f6b591",
      colorPrimary: "#ed6b23",
      colorPrimaryBorder: "#f6b591",
    },
    Input: {
      activeBorderColor: "#293134",
      hoverBorderColor: "#333d41",
      colorPrimaryActive: "#c6591d",
      colorPrimaryHover: "#f08448",
    },
    Select: {
      activeBorderColor: "#293134",
      hoverBorderColor: "#333d41",
      optionActiveBg: "#F4F6F6",
      optionSelectedBg: "#F4F6F6",
    },
  },
};
